name: eats_client
description: ""

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  # Local packages
  eats_core:
    path: ../eats_core

  # Essentials
  intl: ^0.17.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.2
  # sentry_flutter: ^6.5.1
  package_info_plus: ^3.0.2

  # State Management
  flutter_riverpod: ^2.0.2
  riverpod_generator: ^1.0.4
  riverpod_annotation: ^1.0.4

  # Native
  flutter_native_splash: ^2.2.6

  # Freezed
  freezed_annotation: ^2.2.0
  json_annotation:
    ^4.8.0

    #UI
  lottie: ^1.4.1
  flutter_screenutil: ^5.5.3+2
  another_transformer_page_view: ^2.0.1


  #payment

  logger_flutter:
    git:
      url: https://github.com/GarageAppTeam/logger_flutter.git
      ref: master # branch name

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Freezed
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  app_rename: ^0.0.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/logos/
    - assets/svg/
    - assets/languages/
    - assets/lottie/

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
          weight: 300

        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500

        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400

        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700

        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 800

    - family: eats_icons
      fonts:
        - asset: assets/icons/eats_icons.ttf
